### PR TITLE
Adding Chinese (traditional-Taiwan) 

### PR DESCRIPTION
**Pull request by silverbow1**
[zh-TW.zip](https://github.com/snipcart/snipcart-localization/files/2948313/zh-TW.zip)

### CODE REVIEW

**Comment by JeanSebTr** [comment]
Hi @silverbow1 

Thanks for contributing!

Could you add the file directly to the `locales` folder and base your work on the `master` branch?

**Comment by silverbow1** [comment]
Hello,

Yes, no problem, I'd like to do it, however I cannot upload file (I tried today).
Seems I can only do another push request.
Regards


Le lun. 11 mars 2019 à 23:16, Jean-Sébastien Tremblay <notifications@github.com<mailto:notifications@github.com>> a écrit :

Hi @silverbow1<https://github.com/silverbow1>

Thanks for contributing!

Could you add the file directly to the locales folder and base your work on the master branch?

**Comment by JeanSebTr** [comment]
You can click "Create new file" [from that page directly](https://github.com/snipcart/snipcart-localization/tree/master/locales).
image

You'll then be able to propose the changes as a new Pull Request.


I hope this helps!

**Comment by silverbow1** [comment]
Hello,

Ok it is done.
It seems I did it 2 times. One time empty (first time, I thought I could upload after), second time is correct. I apologize for that. Now I know.


About that, I tried to change the language in my website, following your instructions from your website, however, I cannot see any change, it’s still English.
I checked several times, including for minor details that could be disturbing (as the $) for the last time) but I cannot see anything.

Any suggestion ?

Regards

Alexis

________________________________

**Comment by JeanSebTr** [comment]
Thanks!

I've commented on PR #91 – it's almost ready to be merged 🙂 

You can open a discussion on our support channel (login to the dashboard and you'll see the Intercom icon in the lower left corner). We'll be able to check with you why it doesn't work on your website!

**Pull request closed without merging**
