### PR TITLE
Update cs-CZ.js

### PR DESCRIPTION
**Pull request by illycz**
Some locale improvements

### CODE REVIEW

**Comment by illycz** [comment]
Any news? Thanks!

**Comment by JeanSebTr** [comment]
I'll merge this in the cart in a few minutes. It should be live soon.

**Comment by illycz** [comment]
@JeanSebTr  Console give me this:
image

And I still see old translation:
image

Any suggestion? Do I missing something? I'm only set HTML lang attr to `cs_CZ`.

Thanks

**Comment by JeanSebTr** [comment]
My fault. Forgot to apply the changes to the cart after merging the PR.

We'll automate this process soon. The updated cs-CZ file is now live.

**Pull request merged**
